### ISSUE TITLE
incorrect size for PlainHamburgerMenuButton

### ISSUE THREAD

**Issue by geonanorch** [elix/elix#120]
Just a small glitch: the style for `PlainHamburgerMenuButton` goes

```css
          :host {
            height: 1em;
            width: 1em;
          }

          [part~="menu-icon"] {
            display: block;
            height: 24px;
            width: 24px;
          }
```

So the size of the host is set to a value different (usually smaller) then the size of the contained icon, causing the icon to overflow and be misaligned in its container. Removing the `:host` styling fixes the issue.
