### ISSUE TITLE
PopupSource break ListComboBox

### ISSUE THREAD

**Issue by BlackGlory** [elix/elix#162]
This bug cannot be reproduced on codepen, please create an html file manually and open it in a browser.

```html
<script type="module" src="https://cdn.jsdelivr.net/gh/elix/elix@main/define/ListComboBox.js"></script>

<elix-list-combo-box>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</elix-list-combo-box>
```

![Snipaste_2021-01-15_18-37-17](https://user-images.githubusercontent.com/1365962/104714911-bf20b200-5760-11eb-96ff-4a75ea12897e.png)

The component will be displayed incorrectly, and the list cannot be opened. If you turn off PopupSource's height style, it returns to normal.

```css
[part~="source"] {
    height: 100%; /* this line */
    -webkit-tap-highlight-color: transparent;
    touch-action: manipulation;
    width: 100%;
}
```
